version: '3.1'

services:
  web:
    restart: always
    image: music_app
    build: .
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
      - migration
    volumes:
      - ./data/django-web:/usr/src/app
      - ./data/django-static:/usr/src/app/static
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000

  migration:
    image: music_app
    command: python manage.py migrate --noinput
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music_application_db
    volumes:
      - ./data/db:/var/lib/postgresql/data