# Generated by Django 4.1.7 on 2023-03-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0010_alter_album_name_alter_artist_name_and_more'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_tracks',
            field=models.ManyToManyField(related_name='user_likes', to='music_app.track'),
        ),
    ]
