# Generated by Django 4.1.7 on 2023-03-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_favorite_tracks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorite_tracks',
            new_name='favourite_tracks',
        ),
    ]
