# Generated by Django 4.1.7 on 2023-03-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='explicit',
            new_name='is_explicit',
        ),
        migrations.AddField(
            model_name='album',
            name='album_image_url',
            field=models.URLField(default='https://i.scdn.co/image/ab6761610000e5ebd8376ce81f532aa5aeec96a1', verbose_name='Album image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='is_full_record',
            field=models.BooleanField(default=False, verbose_name='Full record about album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image_url',
            field=models.URLField(default='https://i.scdn.co/image/ab6761610000e5ebd8376ce81f532aa5aeec96a1', verbose_name='Artist image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='is_full_record',
            field=models.BooleanField(default=False, verbose_name='Full record about artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='is_full_record',
            field=models.BooleanField(default=False, verbose_name='Full record about track'),
            preserve_default=False,
        ),
    ]
