# Generated by Django 4.1.7 on 2023-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_rename_explicit_track_is_explicit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_full_record',
            field=models.BooleanField(default=False, verbose_name='Full record about album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_full_record',
            field=models.BooleanField(default=False, verbose_name='Full record about artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_full_record',
            field=models.BooleanField(default=False, verbose_name='Full record about track'),
        ),
    ]
