# Generated by Django 4.1.7 on 2023-03-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_alter_album_copyrights_alter_album_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_image_url',
            field=models.URLField(null=True, verbose_name='Album image URL'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image_url',
            field=models.URLField(null=True, verbose_name='Artist image URL'),
        ),
        migrations.AlterField(
            model_name='externalid',
            name='name',
            field=models.CharField(max_length=30, verbose_name='External ID name'),
        ),
    ]
