# Generated by Django 4.1.7 on 2023-03-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_alter_album_album_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='copyrights',
            field=models.ManyToManyField(related_name='albums', to='music_app.copyrightalbum'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='albums', to='music_app.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='artists', to='music_app.genre'),
        ),
        migrations.AlterField(
            model_name='copyrightalbum',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Copyright text'),
        ),
    ]
