# Generated by Django 4.1.7 on 2023-03-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_alter_track_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Album name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Group name'),
        ),
        migrations.AlterField(
            model_name='copyrightalbum',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Copyright text'),
        ),
        migrations.AlterField(
            model_name='externalid',
            name='name',
            field=models.CharField(max_length=50, verbose_name='External ID name'),
        ),
        migrations.AlterField(
            model_name='externalid',
            name='value',
            field=models.CharField(max_length=50, verbose_name='External ID value'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Track name'),
        ),
    ]
