# Generated by Django 4.1.7 on 2023-03-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_alter_album_name_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Track name'),
        ),
    ]
