# Generated by Django 4.1.7 on 2023-03-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_alter_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Album name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Group name'),
        ),
        migrations.AlterField(
            model_name='copyrightalbum',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Copyright text'),
        ),
    ]
